name: Main Deploy
on: 
  push:
    branches:
      - '*'
    paths:
      - 'prod/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TERRAFORM_ENV_BASE64: ${{ secrets.TERRAFORM_ENV_BASE64 }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - run: |-
        _tfdir=prod
        echo $TERRAFORM_ENV_BASE64 | base64 -d > ${_tfdir}/terraform.tfvars
        terraform -chdir=${_tfdir} init
        terrraform -chdir=${_tfdir} plan
    - run: |-
        echo "Plan output:"
        echo ${{ steps.plan.outputs.stdout }}
        echo ""
        echo "Plan Errors:"
        echo ${{ steps.plan.outputs.stderr }}
        echo ""
        echo "Plan exit code"
        echo ${{ steps.plan.outputs.exitcode }}